# Generated by Django 4.1.2 on 2022-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_comment_table_menu_is_published_alter_menu_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
