# Generated by Django 4.1.2 on 2022-12-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='menu',
            name='discountQuantityPrice',
            field=models.IntegerField(default=0, verbose_name='Discount Quantity Price'),
        ),
    ]
