# Generated by Django 4.1.2 on 2023-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_menu_discount_menu_discountquantityprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='customer_image',
            field=models.ImageField(default='', upload_to='comment', verbose_name='Customer-image'),
        ),
    ]
